export { default as smileysEmotion } from './smileys-emotion.svg?raw';
export { default as peopleBody } from './people-body.svg?raw';
export { default as animalsNature } from './animals-nature.svg?raw';
export { default as foodDrink } from './food-drink.svg?raw';
export { default as travelPlaces } from './travel-places.svg?raw';
export { default as activities } from './activities.svg?raw';
export { default as objects } from './objects.svg?raw';
export { default as symbols } from './symbols.svg?raw';
export { default as flags } from './flags.svg?raw';
